### ISSUE TITLE
mp3 file size

### ISSUE THREAD

**Issue by vcrepin** [ScottMichaud/AudioSampleLoader#3]
This is more a question than an issue.

What is the max file size that we can use for an mp3 file ?

I tried with 30k files and it complains that the source is too large.

Thank you!

**Comment by ScottMichaud** [comment]
That would depend on your browser, I expect. It blindly passes the blob to the browser's decode engine.

**Comment by vcrepin** [comment]
Ok thanks. I'll experiment with various sizes.

**Comment by ScottMichaud** [comment]
Are you referring to the number of files in a batch, or the size of an individual file?

Either way, AudioSampleLoader doesn't look at either. If "30k files" refers to 30,000 files, then I haven't tested that many, but I also don't even really keep track of that. It should be fine as long as you don't run out of memory. I might have a bug, though. Never know. I'd expect that the browser ran out of memory, though.

If you mean a given size of MP3 file, then it depends on the browser. I blindly send a data blob to the browser's audio decode engine. Various browsers will be more or less picky. Like, at one point about three years ago, a Firefox update broke all MP3s in WebAudio API for me (but it worked elsewhere in the browser, like in an audio element). They've since fixed it. Pretty much anything could throw it off, and do so inconsistently. That's all the browser, though.

**Comment by vcrepin** [comment]
Hello. If I may ask you another question...

I'm using your library and it works great. But when I leave the browser inactive for a long time and start using the library again, the sound doesn't play anymore. And no error are shown. I even tried to reset the api (by instantiating it again and loading the source file as if it was the first time) but nothing does the trick.

I know it is quite vague but if it rings you a bell about something it would be appreciated.

**Comment by vcrepin** [comment]
Precision: I must completely kill  and restart the application (it is an android cordova app) for the sound to play again.

**Comment by ScottMichaud** [comment]
Doesn't ring a bell, unfortunately. That said, I haven't used Cordova -- my phone runs Android 2.2, so it's pretty much an antique. Besides, most of my programming tasks involve C++ these days.

That said, AudioSampleLoader is just glue around XMLHttpRequest and Web Audio. After it runs, it has references to your decoded audio files. If those disappear, it would pretty much have to be because Cordova garbage collected that portion of your application. The confusing part is that you said you can't just re-download them. That sounds like Cordova is giving up for some reason.

How much memory is your app using at the time it refuses to load audio? Is the app leaking memory such that it, over time, gets to the point where Cordova basically just pulls the plug?

**Comment by vcrepin** [comment]
I do not see signs of memory problems when it happens. What I suspect is the AudioContext being modified by the browser for an unknown reason. What I will try is to close the audiocontext et reopen it between each invocation. 

I'll keep you posted.

**Comment by ScottMichaud** [comment]
That shouldn't be an issue. Are you copying the AudioBuffer references into your application's objects? Or are you just reading them from AudioSampleLoader whenever you need them?

**Comment by vcrepin** [comment]
I'm just reading them from AudioSampleLoader. 

var service = this,
    metronome = {
      metronomeOn: false,
      metronomeRate: 60
    },
    metronomeBuffer,
      metronomeSource = null,
      AudioContext = $window.AudioContext || $window.webkitAudioContext,
      audioCtx = new AudioContext(),
      audioLoader = null;

```
service.toggleMetronome = function (metronomeOn, sound, loop, tempo) {
  if(tempo)
    metronome.metronomeRate = Number(metronome.metronomeRate) + Number(tempo);
  if (metronomeOn == true) {
    audioCtx = new AudioContext();
    startMetronome(metronome.metronomeRate, sound, loop);
  } else {
    metronomeSource.stop(0);
    metronome.metronomeOn = false;
    audioCtx.close();
  }
};

function startMetronome (bpm, sound, loop) {
  audioLoader = new AudioSampleLoader();
  audioLoader.src = sound;
  audioLoader.ctx = audioCtx;

  audioLoader.onload = function() {
    metronomeBuffer = audioLoader.response;
    prepareMetronome(bpm, loop);
    metronomeSource.start(0);
  };
  audioLoader.onerror = function() {
    $log.error("Error loading Metronome Audio");
  };
  audioLoader.send();
}

function prepareMetronome (bpm, loop)   {
  var frameCount = audioCtx.sampleRate * (60/bpm);
  var numberOfChannels = metronomeBuffer.numberOfChannels;
  var paddingBuffer = audioCtx.createBuffer(1, frameCount, audioCtx.sampleRate);
  for (var i=0; i<numberOfChannels; i++) {
    var clickData = paddingBuffer.getChannelData(i);
    clickData.set(metronomeBuffer.getChannelData(i));
  }
  metronomeSource = audioCtx.createBufferSource();
  metronomeSource.connect(audioCtx.destination);
  metronomeSource.buffer = paddingBuffer;
  metronomeSource.loop = loop;
}
```

**Comment by ScottMichaud** [comment]
Yeah I can't see anything at the moment.

Try adding a temporary log statement in the top of startMetronome()'s contents, in the contents of audioLoader.onload's anonymous callback, in the top of prepareMetronome()'s contents, right before metronomeSource.start(0), and right after metronomeSource.start(0). Let's see if JavaScript is dying due to an undefined reference.

It'd obviously be better to add a breakpoint and just inspect the values, but I'm not sure what Cordova allows for that. Most of my experience is with Firefox tools.

**Comment by ScottMichaud** [comment]
Closing the issue. The last message just past its 3-year anniversary.
